/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef MVMSTATEMACHINE_H_
#define MVMSTATEMACHINE_H_


#include <HAL.h>
#include "sc_types.h"
#include "StatemachineInterface.h"
#include "TimedStatemachineInterface.h"

/*! \file Header of the state machine 'MVMStateMachine'.
*/


/*! Define indices of states in the StateConfVector */
#define SCVI_MAIN_REGION_INSPIRATION 0
#define SCVI_MAIN_REGION_EXPIRATION 0


class MVMStateMachine : public TimedStatemachineInterface, public StatemachineInterface
{
	public:
		MVMStateMachine();
		
		virtual ~MVMStateMachine();
		
		/*! Enumeration of all states */ 
		typedef enum
		{
			MVMStateMachine_last_state,
			main_region_Inspiration,
			main_region_Expiration
		} MVMStateMachineStates;
					
		static const sc_integer numStates = 2;
		
		//! Inner class for default interface scope.
		class DefaultSCI
		{
			public:
				/*! Gets the value of the variable 'hal' that is defined in the default interface scope. */
				HAL * get_hal() const;
				
				/*! Sets the value of the variable 'hal' that is defined in the default interface scope. */
				void set_hal(HAL * value);
				
				
				
			private:
				friend class MVMStateMachine;
				HAL * hal;
				
				
		};
		
		/*! Returns an instance of the interface class 'DefaultSCI'. */
		DefaultSCI* getDefaultSCI();
		
		/*! Gets the value of the variable 'hal' that is defined in the default interface scope. */
		HAL * get_hal() const;
		
		/*! Sets the value of the variable 'hal' that is defined in the default interface scope. */
		void set_hal(HAL * value);
		
		
		/*
		 * Functions inherited from StatemachineInterface
		 */
		virtual void init();
		
		virtual void enter();
		
		virtual void exit();
		
		virtual void runCycle();
		
		/*!
		* Checks if the state machine is active (until 2.4.1 this method was used for states).
		* A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
		*/
		virtual sc_boolean isActive() const;
		
		
		/*!
		* Checks if all active states are final. 
		* If there are no active states then the state machine is considered being inactive. In this case this method returns false.
		*/
		virtual sc_boolean isFinal() const;
		
		/*
		 * Functions inherited from TimedStatemachineInterface
		 */
		virtual void setTimer(TimerInterface* timerInterface);
		
		virtual TimerInterface* getTimer();
		
		virtual void raiseTimeEvent(sc_eventid event);
		
		virtual sc_integer getNumberOfParallelTimeEvents();
		
		/*! Checks if the specified state is active (until 2.4.1 the used method for states was calles isActive()). */
		sc_boolean isStateActive(MVMStateMachineStates state) const;
		
		//! number of time events used by the state machine.
		static const sc_integer timeEventsCount = 2;
		
		//! number of time events that can be active at once.
		static const sc_integer parallelTimeEventsCount = 1;
		
		
	protected:
		
		
	private:
		MVMStateMachine(const MVMStateMachine &rhs);
		MVMStateMachine& operator=(const MVMStateMachine&);
		
		
		//! the maximum number of orthogonal states defines the dimension of the state configuration vector.
		static const sc_ushort maxOrthogonalStates = 1;
		
		TimerInterface* timer;
		sc_boolean timeEvents[timeEventsCount];
		
		
		MVMStateMachineStates stateConfVector[maxOrthogonalStates];
		
		sc_ushort stateConfVectorPosition;
		
		DefaultSCI iface;
		
		// prototypes of all internal functions
		
		void enact_main_region_Inspiration();
		void enact_main_region_Expiration();
		void exact_main_region_Inspiration();
		void exact_main_region_Expiration();
		void enseq_main_region_Inspiration_default();
		void enseq_main_region_Expiration_default();
		void enseq_main_region_default();
		void exseq_main_region_Inspiration();
		void exseq_main_region_Expiration();
		void exseq_main_region();
		void react_main_region__entry_Default();
		sc_boolean react();
		sc_boolean main_region_Inspiration_react(const sc_boolean try_transition);
		sc_boolean main_region_Expiration_react(const sc_boolean try_transition);
		void clearInEvents();
		void clearOutEvents();
		
		
		
		
};




#endif /* MVMSTATEMACHINE_H_ */
